AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Jersey API - devsimiyu.samserverless::api
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: devsimiyu.samserverless.api.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: api
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ApiApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: ApiApi
